Vagrant.configure("2") do |config|
  config.vm.define "app" do |node|
    node.vm.box = "bento/centos-7"
    node.vm.hostname = "app"
    node.vm.network :private_network, ip: "192.168.33.10"
  end
end